name: stepfunction-rerun
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - abseil-cpp=20200225.2
  - arrow-cpp=3.0.0
  - asn1crypto=1.4.0
  - awswrangler=2.8.0
  - backcall=0.2.0
  - beautifulsoup4=4.9.3
  - boost-cpp=1.69.0
  - boto3=1.17.46
  - botocore=1.20.78
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.7
  - decorator=5.0.9
  - double-conversion=3.1.5
  - et_xmlfile=1.0.1
  - gflags=2.2.2
  - glog=0.4.0
  - grpc-cpp=1.28.1
  - icu=58.2
  - idna=2.10
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jdcal=1.4.1
  - jedi=0.17.0
  - jmespath=0.10.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libboost=1.73.0
  - libcblas=3.9.0
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libprotobuf=3.11.4
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libthrift=0.13.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - lxml=4.6.3
  - lz4-c=1.9.3
  - ncurses=6.2
  - numpy=1.19.4
  - openpyxl=3.0.7
  - openssl=1.1.1k
  - orc=1.6.5
  - pandas=1.1.4
  - parso=0.8.2
  - pexpect=4.8.0
  - pg8000=1.19.5
  - pickleshare=0.7.5
  - pip=21.1.1
  - prompt-toolkit=3.0.17
  - ptyprocess=0.7.0
  - pyarrow=3.0.0
  - pycparser=2.20
  - pygments=2.9.0
  - pymysql=1.0.2
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.8.10
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pyzmq=20.0.0
  - re2=2020.11.01
  - readline=8.1
  - redshift_connector=2.0.881
  - requests=2.25.1
  - s3transfer=0.3.6
  - scramp=1.4.0
  - setuptools=52.0.0
  - six=1.15.0
  - snappy=1.1.8
  - soupsieve=2.0.1
  - sqlite=3.35.4
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - uriparser=0.9.3
  - urllib3=1.26.4
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.4.5
